import { GoogleGenerativeAI } from "@google/generative-ai";

const apiKey = process.env.GEMINI_API_KEY!;
const genAI = new GoogleGenerativeAI(apiKey);

export const model = genAI.getGenerativeModel({
  model: "gemini-1.5-flash",
});

export const generationConfig = {
  temperature: 1,
  topP: 0.95,
  topK: 64,
  maxOutputTokens: 8192,
  responseMimeType: "text/plain",
};

export const parts = [
  {
    text: "input: **User:**\n\n* Gender: Male\n* Age: 25\n* Height: 180\n* Weight: 60\n* Family history of overweight: No\n* Frequently consumes high-calorie food: Yes\n* Frequency of vegetable consumption: Sometimes\n* Number of main meals: 1 or 2 meals\n* Consumption of food between meals: No\n* Smokes: No\n* Daily water consumption: 1-2 liters\n* Monitors calorie intake: No\n* Frequency of physical activity: 1-2 days a week\n* Time using electronic devices: 3-5 hours\n* Consumes alcohol: Never\n* Type of transportation used: Automobile\n\n**Level:** insufficient weight",
  },
  {
    text: "output: **Analysis:** Based on your input, you are classified as insufficient weight.\n\n**Suggestions:**\n\n* **Workout Tips:** Focus on strength training exercises to build muscle mass. Consider consulting a certified trainer for a personalized plan.\n* **Nutrition Planner:** Increase your daily calorie intake by incorporating healthy, high-calorie foods like nuts, avocados, and whole grains. Aim for at least 3 balanced meals with healthy snacks throughout the day.\n* **Additional notes:** Drinking plenty of water and getting enough sleep are crucial for healthy weight gain.",
  },
  {
    text: "input: **User:**\n\n* Gender: Female\n* Age: 40\n* Height: 165\n* Weight: 58\n* Family history of overweight: Yes\n* Frequently consumes high-calorie food: No\n* Frequency of vegetable consumption: Sometimes\n* Number of main meals: 3 meals\n* Consumption of food between meals: Sometimes\n* Smokes: No\n* Daily water consumption: more than 2 liters\n* Monitors calorie intake: No\n* Frequency of physical activity: 3-4 days a week\n* Time using electronic devices: 0-2 hours\n* Consumes alcohol: Sometimes\n* Type of transportation used: Walking\n\n**Level:** Normal weight",
  },
  {
    text: "output: **Analysis:** Based on your input, you are classified as Normal weight.\n\n**Suggestions:**\n\n* **Workout Tips:** Maintain your current activity level or consider incorporating more cardio exercises for overall fitness.\n* **Nutrition Planner:** Continue your healthy eating habits with a focus on portion control and a balanced diet rich in fruits, vegetables, and whole grains.\n* **Additional notes:** Monitor your weight regularly and adjust your diet or exercise routine if needed.  Given your family history, maintaining a healthy lifestyle is key.",
  },
  {
    text: "input: **User:**\n\n* Gender: Male\n* Age: 35\n* Height: 175\n* Weight: 85\n* Family history of overweight: No\n* Frequently consumes high-calorie food: Yes\n* Frequency of vegetable consumption: Sometimes\n* Number of main meals: 3 meals\n* Consumption of food between meals: Sometimes\n* Smokes: No\n* Daily water consumption: 1-2 liters\n* Monitors calorie intake: No\n* Frequency of physical activity: 1-2 days a week\n* Time using electronic devices: 3-5 hours\n* Consumes alcohol: Sometimes\n* Type of transportation used: Automobile\n\n**Level:** Overweight 1",
  },
  {
    text: "output: **Analysis:** Based on your input, you are classified as Overweight 1.\n\n**Suggestions:**\n\n* **Workout Tips:** Increase your physical activity level by incorporating moderate-intensity exercise for at least 30 minutes most days of the week. Consider activities you enjoy like brisk walking, biking, or swimming.\n* **Nutrition Planner:** Reduce your overall calorie intake by focusing on portion control and limiting sugary drinks and processed foods. Aim to include more fruits, vegetables, and whole grains in your diet.\n* **Additional notes:** Drinking more water can help with feeling full and reducing cravings. Consider reducing snacking between meals.",
  },
  {
    text: "input: **User:**\n\n* Gender: Male\n* Age: 40\n* Height: 175\n* Weight: 92\n* Family History of Overweight: Yes\n* Frequently Consumed High-Calorie Food: Yes\n* Frequency of Consumption of Vegetables: Sometimes\n* Number of Main Meals: 3 meals\n* Consumption of Food between Meals: Frequently\n* Smoke: No\n* Consumption of Water Daily: Less than 1 liter\n* Monitor Calorie Intake: No\n* Frequency of Physical Activity: No physical activity\n* Time Using Electronic Devices: More than 5 hours\n* Consumption of Alcohol: Sometimes\n* Type of Transportation Used: Automobile\n\n**Level:** Overweight 2",
  },
  {
    text: "output: **Analysis:** Based on your input, you are classified as Overweight 2.\n\n**Suggestions:**\n\n* **Workout Tips:**  Start with light physical activity like brisk walking or swimming for 30 minutes, 3-4 days a week. Gradually increase the duration and intensity as you build strength and stamina. Consider joining a fitness class or seeking guidance from a certified trainer for a personalized workout plan.\n* **Nutrition Planner:**  Reduce your calorie intake by focusing on portion control and limiting sugary drinks, processed foods, and unhealthy snacks. Aim to include more fruits, vegetables, and whole grains in your diet. Consult a registered dietitian for a personalized meal plan that suits your needs and preferences.\n* **Additional notes:**  Increasing your water intake is crucial for overall health and weight management. Aim for at least 2 liters of water per day.  Consider reducing your time spent using electronic devices and prioritizing active leisure activities.  Given your family history, maintaining a healthy lifestyle is essential.",
  },
  {
    text: "input: **User:**\n\n* Gender: Female\n* Age: 16\n* Height: 160\n* Weight: 52\n* Family History of Overweight: No\n* Frequently Consumed High-Calorie Food: Sometimes\n* Frequency of Consumption of Vegetables: Always\n* Number of Main Meals: 3 meals\n* Consumption of Food between Meals: Sometimes\n* Smoke: No\n* Consumption of Water Daily: 1-2 liters\n* Monitor Calorie Intake: No\n* Frequency of Physical Activity: 1-2 days a week\n* Time Using Electronic Devices: 3-5 hours\n* Consumption of Alcohol: Never\n* Type of Transportation Used: Walking\n\n**Level:** Normal weight",
  },
  {
    text: "output: **Analysis:** Based on your input, you are classified as Normal weight.\n\n**Suggestions:**\n\n* **Workout Tips:**  While you are within a healthy weight range, increasing your physical activity to at least 3-4 days a week would be beneficial for your overall health and well-being.  Consider activities you enjoy like dancing, team sports, or joining a fitness class.\n* **Nutrition Planner:**  Continue your healthy eating habits, focusing on portion control and a balanced diet rich in fruits, vegetables, and whole grains.  \n* **Additional notes:** It's great that you already eat plenty of vegetables. Maintaining this healthy habit is important.   Given your age, ensuring you get enough calcium and vitamin D through your diet or supplements is crucial for bone health.",
  },
  {
    text: "input: **User:**\n\n* Gender: Female\n* Age: 22\n* Height: 170\n* Weight: 55 \n* Family History of Overweight: No\n* Frequently Consumed High-Calorie Food: Rarely\n* Frequency of Consumption of Vegetables: Sometimes\n* Number of Main Meals: 2 meals\n* Consumption of Food between Meals: No\n* Smoke: No\n* Consumption of Water Daily: 1-2 liters\n* Monitor Calorie Intake: No\n* Frequency of Physical Activity: 3-4 days a week\n* Time Using Electronic Devices: 3-5 hours\n* Consumption of Alcohol: Rarely\n* Type of Transportation Used: Public transportation\n\n**Level:** Underweight",
  },
  {
    text: "output: **Analysis:** Based on your input, you are classified as Underweight.\n\n**Suggestions:**\n\n* **Workout Tips:**  Focus on building muscle mass through strength training exercises. Consider consulting a certified trainer for a personalized plan that helps you gain weight healthily.\n* **Nutrition Planner:**  Increase your calorie intake by incorporating healthy, high-calorie foods like nuts, avocados, dried fruits, and whole grains. Aim for at least 3 balanced meals with healthy snacks throughout the day.\n* **Additional notes:** Drinking plenty of water and getting enough sleep are crucial for healthy weight gain.  Consider adding protein shakes or smoothies to your diet to boost calorie intake.  It's important to note that gaining weight too quickly can be unhealthy, so focus on gradual, sustainable changes.",
  },
  {
    text: "input: **User:**\n\n* Gender: Male\n* Age: 65\n* Height: 180\n* Weight: 115\n* Family History of Overweight: Yes\n* Frequently Consumed High-Calorie Food: Sometimes\n* Frequency of Consumption of Vegetables: Always\n* Number of Main Meals: 3 meals\n* Consumption of Food between Meals: No\n* Smoke: No\n* Consumption of Water Daily: More than 2 liters\n* Monitor Calorie Intake: No\n* Frequency of Physical Activity: 3-4 days a week\n* Time Using Electronic Devices: 0-2 hours\n* Consumption of Alcohol: Never\n* Type of Transportation Used: Walking\n\n**Level:** Obesity Level 2",
  },
  {
    text: "output: **Analysis:** Based on your input, you are classified as Obesity Level 2.\n\n**Suggestions:**\n\n* **Workout Tips:**  Start with light physical activity like brisk walking or swimming for 30 minutes, 3-4 days a week. Gradually increase the duration and intensity as you build strength and stamina. Consider joining a fitness class or seeking guidance from a certified trainer for a personalized workout plan tailored to your age and fitness level.  \n* **Nutrition Planner:**  Reduce your calorie intake by focusing on portion control and limiting sugary drinks, processed foods, and unhealthy snacks. Aim to include more fruits, vegetables, and whole grains in your diet. Consult a registered dietitian for a personalized meal plan that suits your needs and preferences, considering your family history.\n* **Additional notes:**  Maintaining a healthy weight is crucial at your age, as it helps prevent age-related health issues.  Given your family history of overweight, prioritize making sustainable lifestyle changes for long-term health.  Consider engaging in activities you enjoy, like gardening, to keep you active and motivated.",
  },
  {
    text: "input: **User:**\n\n* Gender: Female\n* Age: 35\n* Height: 165\n* Weight: 58\n* Family History of Overweight: No\n* Frequently Consumed High-Calorie Food: Rarely\n* Frequency of Consumption of Vegetables: Daily\n* Number of Main Meals: 3 meals\n* Consumption of Food between Meals: No\n* Smoke: No\n* Consumption of Water Daily: More than 2 liters\n* Monitor Calorie Intake: Yes\n* Frequency of Physical Activity: 5 or more days a week\n* Time Using Electronic Devices: 0-2 hours\n* Consumption of Alcohol: Never\n* Type of Transportation Used: Bike\n\n**Level:** Normal weight",
  },
  {
    text: "output: **Analysis:** Based on your input, you are classified as Normal weight.\n\n**Suggestions:**\n\n* **Workout Tips:**  You are already maintaining a healthy and active lifestyle!  Keep up the great work with your frequent exercise routine. You may consider adding some variety to your workouts to challenge different muscle groups or incorporate interval training for added intensity. \n* **Nutrition Planner:**  You seem to be eating a healthy and balanced diet. Continue focusing on fruits, vegetables, and whole grains. Since you monitor your calorie intake, you are already well-equipped to make adjustments as needed. \n* **Additional notes:** Your healthy habits are commendable.  It's great that you limit your screen time and prioritize active transportation.  Maintaining this lifestyle will contribute to your long-term health and well-being.",
  },
  {
    text: "input: **User:**\n\n* Gender: Male\n* Age: 20\n* Height: 185\n* Weight: 68\n* Family History of Overweight: No\n* Frequently Consumed High-Calorie Food: Occasionally\n* Frequency of Consumption of Vegetables: Sometimes\n* Number of Main Meals: 3 meals\n* Consumption of Food between Meals: Rarely\n* Smoke: No\n* Consumption of Water Daily: 1-2 liters\n* Monitor Calorie Intake: No\n* Frequency of Physical Activity: 5 or more days a week\n* Time Using Electronic Devices: 3-5 hours\n* Consumption of Alcohol: Never\n* Type of Transportation Used: Bike\n\n**Level:** Underweight",
  },
  {
    text: "output: **Analysis:** Based on your input, you are classified as Underweight.\n\n**Suggestions:**\n\n* **Workout Tips:** You are already quite active, but you might consider adding some strength training exercises to help you build muscle mass and increase your weight. Aim for 2-3 strength training sessions per week, focusing on major muscle groups like legs, back, chest, shoulders, and arms.  \n* **Nutrition Planner:**  Increase your calorie intake by incorporating healthy, high-calorie foods like nuts, avocados, dried fruits, and whole grains. Aim for at least 3 balanced meals with healthy snacks throughout the day. Consider adding protein shakes or smoothies to your diet to boost calorie intake.  \n* **Additional notes:** While your current diet may be healthy, you could increase your calorie intake by adding extra portions or including more calorie-dense foods.  Remember, healthy weight gain should be gradual, so don't try to increase your intake too quickly.  Make sure you are getting enough sleep and managing stress levels, as these can also affect your weight.",
  },
  {
    text: "input: **User:**\n\n* Gender: Female\n* Age: 32\n* Height: 170\n* Weight: 63\n* Family History of Overweight: Yes\n* Frequently Consumed High-Calorie Food: Sometimes\n* Frequency of Consumption of Vegetables: Daily\n* Number of Main Meals: 2 meals\n* Consumption of Food between Meals: Sometimes\n* Smoke: No\n* Consumption of Water Daily: Less than 1 liter\n* Monitor Calorie Intake: No\n* Frequency of Physical Activity: 1-2 days a week\n* Time Using Electronic Devices: More than 5 hours\n* Consumption of Alcohol: Occasionally\n* Type of Transportation Used: Public transportation\n \n**Level:** Normal weight",
  },
  {
    text: "output: **Analysis:** Based on your input, you are classified as **Normal weight**.  However, there are some potential areas for improvement.\n\n**Suggestions:**\n\n* **Workout Tips:**  While you are within a healthy weight range, increasing your physical activity to at least 3-4 days a week would be beneficial for your overall health and well-being.  Consider finding activities you enjoy that fit into your busy schedule, like taking a fitness class during your lunch break or going for walks during your workday. \n* **Nutrition Planner:**  You seem to be eating a healthy and balanced diet. However, skipping lunch can lead to overeating later in the day and might disrupt your energy levels. Aim for 3 balanced meals per day, even if you need to pack a lunch for work.  \n* **Additional notes:** You mentioned that your mother is overweight. This can increase your risk of developing overweight or obesity.  Increasing your water intake is important for overall health. Aim for at least 2 liters of water per day.  Try to reduce your screen time and prioritize active leisure activities.  Given your family history, maintaining a healthy lifestyle is essential for long-term health and well-being.",
  },
  {
    text: "input: **User:**\n\n* Gender: Male\n* Age: 45\n* Height: 1.80 meters\n* Weight: 98 kg\n* Family History of Overweight: Yes\n* Frequently Consumed High-Calorie Food: Yes\n* Frequency of Consumption of Vegetables: Rarely\n* Number of Main Meals: More than 3 meals\n* Consumption of Food between Meals: Always\n* Smoke: No\n* Consumption of Water Daily: Less than 1 liter\n* Monitor Calorie Intake: No\n* Frequency of Physical Activity: No physical activity\n* Time Using Electronic Devices: 3-5 hours\n* Consumption of Alcohol: Sometimes\n* Type of Transportation Used: Automobile\n\n**Level:** Overweight 2",
  },
  {
    text: "output: **Analysis:** Based on your input, you are classified as Overweight 2.\n\n**Suggestions:**\n\n* **Workout Tips:**  Start with light physical activity like brisk walking or swimming for 30 minutes, 3-4 days a week. Gradually increase the duration and intensity as you build strength and stamina. Consider joining a fitness class or seeking guidance from a certified trainer for a personalized workout plan tailored to your age and fitness level. \n* **Nutrition Planner:** Reduce your calorie intake by focusing on portion control and limiting sugary drinks, processed foods, and unhealthy snacks. Aim to include more fruits, vegetables, and whole grains in your diet. Consult a registered dietitian for a personalized meal plan that suits your needs and preferences, considering your family history. \n* **Additional notes:**  Increasing your water intake is crucial for overall health and weight management. Aim for at least 2 liters of water per day.  Consider reducing your time spent using electronic devices and prioritizing active leisure activities. Given your family history, maintaining a healthy lifestyle is essential.  Try to incorporate more vegetables into your diet and limit snacking between meals.  \n\nRemember, making gradual and sustainable changes is key to achieving long-term success in your weight management journey.",
  },
  {
    text: "input: **User:**\n\n* Gender: Female\n* Age: 50\n* Height: 1.60 meters\n* Weight: 108 kg\n* Family History of Overweight: No\n* Frequently Consumed High-Calorie Food: Sometimes\n* Frequency of Consumption of Vegetables: Rarely\n* Number of Main Meals: 3 meals\n* Consumption of Food between Meals: Sometimes\n* Smoke: No\n* Consumption of Water Daily: 1-2 liters\n* Monitor Calorie Intake: No\n* Frequency of Physical Activity: Daily\n* Time Using Electronic Devices: 0-2 hours\n* Consumption of Alcohol: Rarely\n* Type of Transportation Used: Public transportation\n\n**Level:** Obesity level 1",
  },
  {
    text: "output: **Analysis:** Based on your input, you are classified as Obesity level 1.\n\n**Suggestions:**\n\n* **Workout Tips:** You are already active, but consider incorporating more intense workouts or longer durations.  Strength training can be particularly helpful for building muscle mass and boosting metabolism.  Consider seeking guidance from a certified trainer to create a personalized program that suits your needs and fitness level.\n* **Nutrition Planner:**  Reduce your calorie intake by focusing on portion control and limiting sugary drinks, processed foods, and unhealthy snacks. Aim to include more fruits, vegetables, and whole grains in your diet. Consult a registered dietitian for a personalized meal plan that suits your needs and preferences.  Increasing your vegetable intake is essential for overall health and can help you feel fuller for longer.\n* **Additional notes:** While you're already drinking a good amount of water, consider increasing it to at least 2 liters per day.  Maintaining a healthy weight is crucial at your age, as it helps prevent age-related health issues.  Given your family history, prioritize making sustainable lifestyle changes for long-term health.  Try to incorporate more vegetables into your diet and limit snacking between meals.  \n\nRemember, making gradual and sustainable changes is key to achieving long-term success in your weight management journey.  You're already on the right track with your daily physical activity. Keep up the good work and focus on making those small changes that can lead to a big difference!",
  },
  {
    text: "input: **User:**\n\n* Gender: Male\n* Age: 68\n* Height: 1.72 meters\n* Weight: 75 kg\n* Family History of Overweight: Yes (father)\n* Frequently Consumed High-Calorie Food: Rarely\n* Frequency of Consumption of Vegetables: Daily\n* Number of Main Meals: 3 meals\n* Consumption of Food between Meals: No\n* Smoke: No\n* Consumption of Water Daily: More than 2 liters\n* Monitor Calorie Intake: No\n* Frequency of Physical Activity: 3-4 days a week (walking, gardening)\n* Time Using Electronic Devices: 0-2 hours\n* Consumption of Alcohol: Never\n* Type of Transportation Used: Walking\n\n**Level:** Normal weight",
  },
  {
    text: "output: **Analysis:** Based on your input, you are classified as **Normal weight**. Your healthy habits, including daily vegetable consumption, moderate physical activity, and minimal screen time, are commendable.\n\n**Suggestions:**\n\n* **Workout Tips:** You're already engaging in regular physical activity with walking and gardening. Consider adding some strength training exercises to your routine 1-2 times a week to help maintain muscle mass and bone density as you age. This could include exercises using resistance bands, bodyweight exercises, or light weights. \n* **Nutrition Planner:** Continue your healthy eating habits with a focus on portion control and a balanced diet rich in fruits, vegetables, and whole grains.  You might consider incorporating more protein into your diet, particularly if you are doing more strength training.\n* **Additional notes:** You mentioned your father was overweight. While your current habits are good, maintaining a healthy lifestyle is key to preventing future weight gain and age-related health issues. Keep up the good work!",
  },
  {
    text: "input: **User:**\n\n* Gender: Female\n* Age: 18\n* Height: 1.75 meters\n* Weight: 59 kg\n* Family History of Overweight: No\n* Frequently Consumed High-Calorie Food: Often\n* Frequency of Consumption of Vegetables: Sometimes\n* Number of Main Meals: 2 meals (often skips breakfast)\n* Consumption of Food between Meals: Sometimes\n* Smoke: No\n* Consumption of Water Daily: Less than 1 liter\n* Monitor Calorie Intake: No\n* Frequency of Physical Activity: 1-2 days a week (sports practice)\n* Time Using Electronic Devices: 3-5 hours\n* Consumption of Alcohol: Never\n* Type of Transportation Used: Public transportation\n\n**Level:** Underweight",
  },
  {
    text: "output: **Analysis:** Based on your input, you are classified as **Underweight**. \n\n**Suggestions:**\n\n* **Workout Tips:**  While you are already engaging in physical activity through sports practice, consider adding some strength training exercises to help you build muscle mass and increase your weight.  Aim for 2-3 strength training sessions per week, focusing on major muscle groups like legs, back, chest, shoulders, and arms. \n* **Nutrition Planner:**  Increase your calorie intake by incorporating healthy, high-calorie foods like nuts, avocados, dried fruits, and whole grains.  Aim for at least 3 balanced meals with healthy snacks throughout the day. Consider adding protein shakes or smoothies to your diet to boost calorie intake.  \n* **Additional notes:**  You mentioned that you often skip breakfast.  It's important to start your day with a nutritious meal to fuel your body.  Consider incorporating breakfast into your routine to ensure you're getting enough calories and nutrients to support your active lifestyle.  Remember, healthy weight gain should be gradual, so don't try to increase your intake too quickly.  Make sure you are getting enough sleep and managing stress levels, as these can also affect your weight.  Also, increase your water intake to at least 2 liters per day.",
  },
  {
    text: "input: **User:**\n\n* Gender: Male\n* Age: 30\n* Height: 1.83 meters\n* Weight: 83 kg\n* Family History of Overweight: No\n* Frequently Consumed High-Calorie Food: Rarely (recently switched to vegetarian diet)\n* Frequency of Consumption of Vegetables: Daily\n* Number of Main Meals: 3 meals\n* Consumption of Food between Meals: Sometimes\n* Smoke: No\n* Consumption of Water Daily: 1-2 liters\n* Monitor Calorie Intake: No\n* Frequency of Physical Activity: No physical activity\n* Time Using Electronic Devices: More than 5 hours\n* Consumption of Alcohol: Occasionally\n* Type of Transportation Used: Automobile\n\n**Level:** Overweight 1",
  },
  {
    text: "output: **Analysis:** Based on your input, you are classified as **Overweight 1**. While you've recently switched to a vegetarian diet and consume vegetables daily, a lack of physical activity and excessive screen time contribute to your weight status.\n\n**Suggestions:**\n\n* **Workout Tips:**  Begin incorporating moderate-intensity exercise into your routine for at least 30 minutes most days of the week. Consider activities you enjoy like brisk walking, biking, or swimming. Even taking the stairs instead of the elevator can make a difference. \n* **Nutrition Planner:**  Continue your vegetarian diet, focusing on portion control and limiting sugary drinks and processed foods. Aim to include a variety of fruits, vegetables, and whole grains. \n* **Additional notes:**  Reducing your time spent using electronic devices and prioritizing active leisure activities will positively impact your health.  Consider finding ways to incorporate movement into your daily routine, such as taking short walks during breaks at work.  \n\nRemember, making gradual and sustainable changes is key to achieving long-term success in your weight management journey.  Your recent shift to a vegetarian diet is commendable.  Adding physical activity will help you maintain a healthy weight and improve your overall well-being.",
  },
  {
    text: "input: **User:**\n\n* Gender: Female\n* Age: 38\n* Height: 1.65 meters\n* Weight: 110 kg\n* Family History of Overweight: Yes (both parents)\n* Frequently Consumed High-Calorie Food: Often\n* Frequency of Consumption of Vegetables: Rarely\n* Number of Main Meals: More than 3 meals (frequent snacking)\n* Consumption of Food between Meals: Always\n* Smoke: No\n* Consumption of Water Daily: Less than 1 liter\n* Monitor Calorie Intake: No\n* Frequency of Physical Activity: Rarely\n* Time Using Electronic Devices: 3-5 hours\n* Consumption of Alcohol: Never\n* Type of Transportation Used: Car (short errands)\n\n**Level:** Obesity level 2",
  },
  {
    text: "output: **Analysis:** Based on your input, you are classified as **Obesity level 2**.  You have a family history of overweight, consume high-calorie foods frequently, rarely consume vegetables, and engage in little physical activity. \n\n**Suggestions:**\n\n* **Workout Tips:** Start with light physical activity like brisk walking for 30 minutes, 3-4 days a week. Gradually increase the duration and intensity as you build strength and stamina.  Consider joining a fitness class or seeking guidance from a certified trainer for a personalized workout plan tailored to your age and fitness level. \n* **Nutrition Planner:**  Reduce your calorie intake by focusing on portion control and limiting sugary drinks, processed foods, and unhealthy snacks. Aim to include more fruits, vegetables, and whole grains in your diet. Consult a registered dietitian for a personalized meal plan that suits your needs and preferences.\n* **Additional notes:** Increasing your water intake is crucial for overall health and weight management. Aim for at least 2 liters of water per day.  Consider reducing your time spent using electronic devices and prioritizing active leisure activities. Given your family history, maintaining a healthy lifestyle is essential.  Try to incorporate more vegetables into your diet and limit snacking between meals.  \n\nRemember, making gradual and sustainable changes is key to achieving long-term success in your weight management journey.  Start with small steps, like replacing one sugary drink per day with water, or incorporating a 15-minute walk into your daily routine. You can gradually build up to more significant changes as you feel more comfortable.  Don't be afraid to seek support from healthcare professionals, such as a doctor, dietitian, or fitness trainer, to guide you on your journey.",
  },
  {
    text: "input: **User:**\n\n* Gender: Male\n* Age: 22\n* Height: 1.78 meters\n* Weight: 72 kg\n* Family History of Overweight: No\n* Frequently Consumed High-Calorie Food: Rarely\n* Frequency of Consumption of Vegetables: Daily\n* Number of Main Meals: 3 meals\n* Consumption of Food between Meals: No\n* Smoke: No\n* Consumption of Water Daily: More than 2 liters\n* Monitor Calorie Intake: Yes\n* Frequency of Physical Activity: 3-4 days a week (gym, sports)\n* Time Using Electronic Devices: 0-2 hours\n* Consumption of Alcohol: Never\n* Type of Transportation Used: Bike\n\n**Level:** Normal weight",
  },
  {
    text: "output: **Analysis:** Based on your input, you are classified as **Normal weight**. Your healthy habits, including daily vegetable consumption, regular exercise, and limited screen time, are commendable.\n\n**Suggestions:**\n\n* **Workout Tips:** You are already maintaining a healthy and active lifestyle with your gym and sports routine.  You might consider adding some variety to your workouts to challenge different muscle groups or incorporating interval training for added intensity.  \n* **Nutrition Planner:**  You seem to be eating a healthy and balanced diet.  Since you monitor your calorie intake, you are already well-equipped to make adjustments as needed. \n* **Additional notes:**  Your healthy habits are commendable.  It's great that you limit your screen time and prioritize active transportation.  Maintaining this lifestyle will contribute to your long-term health and well-being.",
  },
  {
    text: "input: **User:**\n\n* Gender: Male\n* Age: 52\n* Height: 1.80 meters\n* Weight: 87 kg\n* Family History of Overweight: Yes (mother)\n* Frequently Consumed High-Calorie Food: Often (limited healthy options on the road)\n* Frequency of Consumption of Vegetables: Rarely\n* Number of Main Meals: More than 3 meals (irregular eating schedule)\n* Consumption of Food between Meals: Sometimes\n* Smoke: No\n* Consumption of Water Daily: Less than 1 liter\n* Monitor Calorie Intake: No\n* Frequency of Physical Activity: No physical activity (sedentary job)\n* Time Using Electronic Devices: 3-5 hours (during breaks)\n* Consumption of Alcohol: Occasionally\n* Type of Transportation Used: Truck\n\n**Level:** Overweight 1",
  },
  {
    text: "output: **Analysis:** Based on your input, you are classified as **Overweight 1**. You have a family history of overweight, consume high-calorie foods frequently, rarely consume vegetables, have an irregular eating schedule, and lack physical activity. Your sedentary job and limited water intake further contribute to your weight status.\n\n**Suggestions:**\n\n* **Workout Tips:**  Start with light physical activity like brisk walking for 30 minutes, 3-4 days a week.  Gradually increase the duration and intensity as you build strength and stamina.  Consider finding ways to incorporate movement into your workday, such as taking short walks during breaks or using the stairs. \n* **Nutrition Planner:**  Reduce your calorie intake by focusing on portion control and limiting sugary drinks, processed foods, and unhealthy snacks. Aim to include more fruits, vegetables, and whole grains in your diet. Consult a registered dietitian for a personalized meal plan that suits your needs and preferences, considering your limited access to healthy options on the road. \n* **Additional notes:** Increasing your water intake is crucial for overall health and weight management. Aim for at least 2 liters of water per day.  Consider reducing your time spent using electronic devices and prioritizing active leisure activities. Given your family history, maintaining a healthy lifestyle is essential.  \n\nRemember, making gradual and sustainable changes is key to achieving long-term success in your weight management journey.  Start with small steps, like replacing one sugary drink per day with water, or incorporating a 15-minute walk into your daily routine. You can gradually build up to more significant changes as you feel more comfortable.  Don't be afraid to seek support from healthcare professionals, such as a doctor, dietitian, or fitness trainer, to guide you on your journey.",
  },
  {
    text: "input: **User:**\n\n* Gender: Female\n* Age: 62\n* Height: 1.58 meters\n* Weight: 135 kg\n* Family History of Overweight: Yes\n* Frequently Consumed High-Calorie Food: Daily\n* Frequency of Consumption of Vegetables: Rarely\n* Number of Main Meals: 3 meals\n* Consumption of Food between Meals: Often\n* Smoke: No\n* Consumption of Water Daily: Less than 1 liter\n* Monitor Calorie Intake: No\n* Frequency of Physical Activity: No physical activity\n* Time Using Electronic Devices: 3-5 hours\n* Consumption of Alcohol: Never\n* Type of Transportation Used: Car\n\n**Level:** Obesity level 3",
  },
  {
    text: "output: **Analysis:** Based on your input, you are classified as **Obesity level 3**.  You have a family history of overweight, consume high-calorie foods frequently, rarely consume vegetables, and lack physical activity.  Your limited water intake and sedentary lifestyle also contribute to your weight status. \n\n**Suggestions:**\n\n* **Workout Tips:**  Start with very light physical activity like walking for 10-15 minutes, 2-3 days a week. Gradually increase the duration and intensity as you build strength and stamina. Consider consulting a doctor or physical therapist to create a safe and effective exercise plan tailored to your needs and fitness level. \n* **Nutrition Planner:**  Reduce your calorie intake by focusing on portion control and limiting sugary drinks, processed foods, and unhealthy snacks. Aim to include more fruits, vegetables, and whole grains in your diet.  Consult a registered dietitian for a personalized meal plan that suits your needs and preferences.  \n* **Additional notes:** Increasing your water intake is crucial for overall health and weight management. Aim for at least 2 liters of water per day.  Consider reducing your time spent using electronic devices and prioritizing active leisure activities. Given your family history, maintaining a healthy lifestyle is essential.  Try to incorporate more vegetables into your diet and limit snacking between meals.  \n\nRemember, making gradual and sustainable changes is key to achieving long-term success in your weight management journey.  Start with small steps, like replacing one sugary drink per day with water, or incorporating a 5-minute walk into your daily routine. You can gradually build up to more significant changes as you feel more comfortable.  Don't be afraid to seek support from healthcare professionals, such as a doctor, dietitian, or fitness trainer, to guide you on your journey. \n\nIt's important to understand that losing weight at an older age can be more challenging, but it's definitely achievable with dedication and the right support.  Focusing on gradual, sustainable changes, consulting healthcare professionals, and finding activities you enjoy will set you up for success in your weight management journey.",
  },
  {
    text: "input: **User:**\n\n* Gender: Female\n* Age: 25\n* Height: 1.70 meters\n* Weight: 57 kg\n* Family History of Overweight: No\n* Frequently Consumed High-Calorie Food: Often\n* Frequency of Consumption of Vegetables: Daily\n* Number of Main Meals: 3 meals\n* Consumption of Food between Meals: Sometimes\n* Smoke: No\n* Consumption of Water Daily: More than 2 liters\n* Monitor Calorie Intake: No\n* Frequency of Physical Activity: 5 or more days a week (intense dance training)\n* Time Using Electronic Devices: 0-2 hours\n* Consumption of Alcohol: Never\n* Type of Transportation Used: Walking/Public transport (depending on distance)\n\n**Level:** Underweight",
  },
  {
    text: "output: **Analysis:** Based on your input, you are classified as **Underweight**. Despite your active lifestyle, your frequent consumption of high-calorie foods and your occasional snacking might not be providing enough calories to meet your high energy demands.\n\n**Suggestions:**\n\n* **Workout Tips:**  You are already extremely active with your intense dance training.  Continue your routine, but consider adding some strength training exercises to help build muscle mass and increase your weight. Aim for 2-3 strength training sessions per week, focusing on major muscle groups like legs, back, chest, shoulders, and arms.  \n* **Nutrition Planner:**  Increase your calorie intake by incorporating healthy, high-calorie foods like nuts, avocados, dried fruits, and whole grains.  Aim for at least 3 balanced meals with healthy snacks throughout the day. Consider adding protein shakes or smoothies to your diet to boost calorie intake. \n* **Additional notes:**  You mentioned you consume vegetables daily. That's great! Continue this healthy habit.  Remember, healthy weight gain should be gradual, so don't try to increase your intake too quickly.  Make sure you are getting enough sleep and managing stress levels, as these can also affect your weight.  \n\nIt's important to note that you are already quite active, which is fantastic! Your body may have a higher calorie need due to your intense dance training.  Focus on healthy calorie-dense foods to support your activity level and help you gain weight in a healthy way.",
  },
];
